var _custom_tabs_client___custom_tabs_callback_impl_8java =
[
    [ "androidx.browser.customtabs.CustomTabsClient_CustomTabsCallbackImpl", "classandroidx_1_1browser_1_1customtabs_1_1_custom_tabs_client___custom_tabs_callback_impl.html", "classandroidx_1_1browser_1_1customtabs_1_1_custom_tabs_client___custom_tabs_callback_impl" ]
];