var _fragment_manager___on_back_stack_changed_listener_implementor_8java =
[
    [ "mono.androidx.fragment.app.FragmentManager_OnBackStackChangedListenerImplementor", "classmono_1_1androidx_1_1fragment_1_1app_1_1_fragment_manager___on_back_stack_changed_listener_implementor.html", "classmono_1_1androidx_1_1fragment_1_1app_1_1_fragment_manager___on_back_stack_changed_listener_implementor" ]
];