var _google_map___on_info_window_long_click_listener_implementor_8java =
[
    [ "mono.com.google.android.gms.maps.GoogleMap_OnInfoWindowLongClickListenerImplementor", "classmono_1_1com_1_1google_1_1android_1_1gms_1_1maps_1_1_google_map___on_info_window_long_click_listener_implementor.html", "classmono_1_1com_1_1google_1_1android_1_1gms_1_1maps_1_1_google_map___on_info_window_long_click_listener_implementor" ]
];