var _loader___on_load_canceled_listener_implementor_8java =
[
    [ "mono.androidx.loader.content.Loader_OnLoadCanceledListenerImplementor", "classmono_1_1androidx_1_1loader_1_1content_1_1_loader___on_load_canceled_listener_implementor.html", "classmono_1_1androidx_1_1loader_1_1content_1_1_loader___on_load_canceled_listener_implementor" ]
];