var _navigation_bar_view___on_item_selected_listener_implementor_8java =
[
    [ "mono.com.google.android.material.navigation.NavigationBarView_OnItemSelectedListenerImplementor", "classmono_1_1com_1_1google_1_1android_1_1material_1_1navigation_1_1_navigation_bar_view___on_item_selected_listener_implementor.html", "classmono_1_1com_1_1google_1_1android_1_1material_1_1navigation_1_1_navigation_bar_view___on_item_selected_listener_implementor" ]
];