var _popup_menu___on_menu_item_click_listener_implementor_8java =
[
    [ "mono.androidx.appcompat.widget.PopupMenu_OnMenuItemClickListenerImplementor", "classmono_1_1androidx_1_1appcompat_1_1widget_1_1_popup_menu___on_menu_item_click_listener_implementor.html", "classmono_1_1androidx_1_1appcompat_1_1widget_1_1_popup_menu___on_menu_item_click_listener_implementor" ]
];