var _view_pager___on_page_change_listener_implementor_8java =
[
    [ "mono.androidx.viewpager.widget.ViewPager_OnPageChangeListenerImplementor", "classmono_1_1androidx_1_1viewpager_1_1widget_1_1_view_pager___on_page_change_listener_implementor.html", "classmono_1_1androidx_1_1viewpager_1_1widget_1_1_view_pager___on_page_change_listener_implementor" ]
];