var namespace_sensor_app_1_1_database_1_1_data_1_1_c_s_v_handling_1_1_models =
[
    [ "AirQualityMeasurement", "class_sensor_app_1_1_database_1_1_data_1_1_c_s_v_handling_1_1_models_1_1_air_quality_measurement.html", "class_sensor_app_1_1_database_1_1_data_1_1_c_s_v_handling_1_1_models_1_1_air_quality_measurement" ],
    [ "WaterQualityMeasurement", "class_sensor_app_1_1_database_1_1_data_1_1_c_s_v_handling_1_1_models_1_1_water_quality_measurement.html", "class_sensor_app_1_1_database_1_1_data_1_1_c_s_v_handling_1_1_models_1_1_water_quality_measurement" ],
    [ "WeatherMeasurement", "class_sensor_app_1_1_database_1_1_data_1_1_c_s_v_handling_1_1_models_1_1_weather_measurement.html", "class_sensor_app_1_1_database_1_1_data_1_1_c_s_v_handling_1_1_models_1_1_weather_measurement" ]
];