var namespace_sensor_app_1_1_maui_1_1_sensor_app___maui___xaml_type_info =
[
    [ "XamlMetaDataProvider", "class_sensor_app_1_1_maui_1_1_sensor_app___maui___xaml_type_info_1_1_xaml_meta_data_provider.html", "class_sensor_app_1_1_maui_1_1_sensor_app___maui___xaml_type_info_1_1_xaml_meta_data_provider" ]
];