// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SET09102_coursework.Database.Data;

#nullable disable

namespace SET09102_coursework.Database.Migrations
{
    [DbContext(typeof(CourseworkDbContext))]
    partial class CourseworkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SET09102_coursework.Database.Models.Sensor", b =>
                {
                    b.Property<int>("Sensor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sensor_id"));

                    b.Property<DateTime>("Deployment_date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Sensor_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sensor_id");

                    b.ToTable("sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
