name: SensorApp - Build, Unit & Integration Tests

on:
  pull_request:
  push:
    branches: [main]

env:
  DOTNET_VERSION: 8.0.x
  SLN_PATH:      SensorApp/SensorApp.sln
  MAUI_PROJECT:  SensorApp/SensorApp.Maui/SensorApp.Maui.csproj
  TEST_PROJ:     SensorApp/SensorApp.Tests/SensorApp.Tests.csproj

jobs:
  build:
    runs-on: windows-latest
    environment: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore & Build solution
        run: dotnet restore ${{ env.SLN_PATH }} && dotnet build ${{ env.SLN_PATH }} --configuration Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: **/bin/Release/**/*

  unit-tests:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run unit tests
        run: dotnet test ${{ env.TEST_PROJ }} --configuration Release --no-build --logger trx

  integration-tests:
    runs-on: windows-latest
    environment: integration-tests
    needs: build

    env:
      ASPNETCORE_ENVIRONMENT: Testing
      JwtSettings__Key: ${{ secrets.JWT_TEST_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Run integration tests
        run: dotnet test ${{ env.TEST_PROJ }} --configuration Release --no-build --logger trx