name: SensorApp - Build, Unit & Integration Tests
  
on:
  pull_request:
  push:
    branches: [main]

env:
  DOTNET_VERSION: 8.0.x
  SLN_PATH: ${{ vars.SLN_PATH }}
  MAUI_PROJECT: ${{ vars.MAUI_PROJECT }}
  UNIT_TEST_PROJ: ${{ vars.UNIT_TEST_PROJ }}
  INTEGRATION_TEST_PROJ: ${{ vars.INTEGRATION_TEST_PROJ }}

jobs:
  build:
    runs-on: windows-latest
    environment: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install MAUI workloads (Android + Windows)
      run: dotnet workload install maui-android maui-windows

    - name: Restore
      run: dotnet restore ${{ env.SLN_PATH }}

    - name: Build Android
      run: |
        dotnet build ${{ env.MAUI_PROJECT }} \
          -c Release -f net8.0-android

    - name: Build Windows
      run: |
        dotnet build ${{ env.MAUI_PROJECT }} \
          -c Release -f net8.0-windows10.0.19041.0 \
          -p:RuntimeIdentifier=win-x64

    - name: Build solution
      run: dotnet build ${{ env.SLN_PATH }} --configuration Release

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          **/bin/Release/**/*.dll
          **/bin/Release/**/*.exe

  unit-tests:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output

    - name: Run unit tests
      run: dotnet test ${{ env.UNIT_TEST_PROJ }} --configuration Release --no-build --logger trx

  integration-tests:
    runs-on: windows-latest
    environment: integration-tests
    needs: build

    env:
      ASPNETCORE_ENVIRONMENT: Testing
      JwtSettings__Key: ${{ secrets.JWT_TEST_KEY }}

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-output

    - name: Run integration tests
      run: dotnet test ${{ env.INTEGRATION_TEST_PROJ }} --configuration Release --no-build --logger trx
