name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Build Doxygen docs
        run: doxygen Doxyfile

      - name: Upload HTML to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output Page URL
        run: echo "Github pages URL at ${{ steps.deployment.outputs.page_url }}"
